<?php

use Illuminate\Database\Seeder;

class PostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('posts')->insert([
            [
                'category_id'=>1,
                'subcategory_id'=>1,
                'title'=>'movie',
                'slug'=>str_slug('movie'),
                'image'=>'5b320a591a091_KP-Sharma-Oli.jpg',
                'description'=>'this is  the post.......................',
                'keywords'=>'post1',
                'excerpt'=>'This is all about post!!!',
                'user_id'=>1,
                'visitor_id'=>0,
                'status'=>1,
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'category_id'=>1,
                'subcategory_id'=>2,
                'title'=>'Music',
                'slug'=>str_slug('Music'),
                'image'=>'5b309d8399da1_music.jpg',
                'description'=>'this is  the post.......................',
                'keywords'=>'post2',
                'excerpt'=>'This is all about post!!!',
                'user_id'=>0,
                'visitor_id'=>1,
                'status'=>1,
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'category_id'=>2,
                'subcategory_id'=>3,
                'title'=>'national',
                'slug'=>str_slug('national'),
                'image'=>'5b320a591a091_KP-Sharma-Oli.jpg',
                'description'=>'this is  the post.......................',
                'keywords'=>'post3',
                'excerpt'=>'This is all about post!!!',
                'user_id'=>1,
                'visitor_id'=>0,
                'status'=>1,
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'category_id'=>2,
                'subcategory_id'=>4,
                'title'=>'international',
                'slug'=>str_slug('international'),
                'image'=>'5b2b5400e9f17_sher-bahadur-deuba-and-ram-chandra-paudel.jpg',
                'description'=>'this is  the post.......................',
                'keywords'=>'post4',
                'excerpt'=>'This is all about post!!!',
                'user_id'=>1,
                'visitor_id'=>0,
                'status'=>1,
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'category_id'=>3,
                'subcategory_id'=>5,
                'title'=>'Share market',
                'slug'=>str_slug('Share Market'),
                'image'=>'5b374a7a2fc8d_stock.jpg',
                'description'=>'this is  the post.......................',
                'keywords'=>'post5',
                'excerpt'=>'This is all about post!!!',
                'user_id'=>1,
                'visitor_id'=>0,
                'status'=>1,
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'category_id'=>3,
                'subcategory_id'=>6,
                'title'=>'Transportation',
                'slug'=>str_slug('Transportation'),
                'image'=>'5b31e0036ecee_monorail.jpg',
                'description'=>'this is  the post.......................',
                'keywords'=>'post6',
                'excerpt'=>'This is all about post!!!',
                'user_id'=>1,
                'visitor_id'=>0,
                'status'=>1,
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'category_id'=>4,
                'subcategory_id'=>7,
                'title'=>'computer',
                'slug'=>str_slug('Computer'),
                'image'=>'5b33459080c96_DZTbQDGpFD9sFF5BpAHtbU-970-80.jpg',
                'description'=>'this is  the post.......................',
                'keywords'=>'post7',
                'excerpt'=>'This is all about post!!!',
                'user_id'=>1,
                'visitor_id'=>0,
                'status'=>1,
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'category_id'=>4,
                'subcategory_id'=>8,
                'title'=>'Mobile',
                'slug'=>str_slug('Mobile'),
                'image'=>'5b3345822acd7_DZTbQDGpFD9sFF5BpAHtbU-970-80.jpg',
                'description'=>'this is  the post.......................',
                'keywords'=>'post8',
                'excerpt'=>'This is all about post!!!',
                'user_id'=>1,
                'visitor_id'=>0,
                'status'=>1,
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'category_id'=>5,
                'subcategory_id'=>9,
                'title'=>'Football',
                'slug'=>str_slug('Football'),
                'image'=>'5b377b6d2d3ca_skysports-colombia-world-cup_4349161.jpg',
                'description'=>'this is  the post.......................',
                'keywords'=>'post9',
                'excerpt'=>'This is all about post!!!',
                'user_id'=>1,
                'visitor_id'=>0,
                'status'=>1,
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],
            [
                'category_id'=>5,
                'subcategory_id'=>10,
                'title'=>'Cricket',
                'slug'=>str_slug('Cricket'),
                'image'=>'5b377c4b2ee21_skysports-ben-stokes-england-odi-cricket_4241652.jpg',
                'description'=>'this is  the post.......................',
                'keywords'=>'post10',
                'excerpt'=>'This is all about post!!!',
                'user_id'=>1,
                'visitor_id'=>0,
                'status'=>1,
                'created_at' => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),
            ],


        ]);
    }
}
